### ISSUE TITLE
can't compile help plz

### ISSUE THREAD

**Issue by formatme** [A5-/Gamerfood_CSGO#1]
I'm dumb lmafo

**Comment by A5-** [comment]
ok, list me credits with filenames and line numbers of where they should be added and I'll add them.






oh wait I'm not autistic, bye

**Comment by formatme** [comment]
or just add them into a comment? hello? u are autistic u fucking made files for drawmodelexecute IBaseClientDLL etc dumb nigger and you have ur menu in endscene but yet u have a header file for menu.h. **_

> hello????????????????????????????????????????????????????
>  hello????????????????????????????????????????????????????

_**

**Comment by formatme** [comment]
dumb fucking weeb paster so autistic you had to comment right when i posted

**Comment by A5-** [comment]
wanna stop sperging out? bye (this time for good)
