### ISSUE TITLE
GetBonePos broken???

### ISSUE THREAD

**Issue by iBrooda** [A5-/Gamerfood_CSGO#101]
https://gyazo.com/6b0f4222f85e53c07f2aeabd0586ffa5

Im not sure if this is due to broken get bone pos, bone matrix, or setup bones.. but something is defiantly wrong here. (it's aiming where the head would be if x = 0, y = 0 and they were standing

**Comment by SippieCup** [comment]
This is intentionally broken in the release as anti-CP code. its an easy fix if you debug.

**Comment by iBrooda** [comment]
@SippieCup Could you give me a bit more info on what you mean. Do you mean like build as debug or some shit. Like if I start do debug with the "start debug" option in VS I get this error message

https://gyazo.com/6337b04cd7a6f9b6212742f469650388

and as you can see I built it in win32

**Comment by cantbeatme** [comment]
You're trying to execute a dynamic link library (dll) as a program.

**Comment by SippieCup** [comment]
to debug it you need to inject the .dll file into csgo (i'd also suggest adding `-insecure` to the startup path of CS:GO so you don't get banned)

After you inject the .dll into CS:GO, you attach the visual studio code debugger to the CS GO process. and then will be able to debug it.
