### ISSUE TITLE
bitwise

### ISSUE THREAD

**Issue by joolz23** [A5-/Gamerfood_CSGO#102]
you should remove bitwise as they use mark hc simple base, not your code.

**Comment by cantbeatme** [comment]
https://youtu.be/T4T4hFQyEp4?t=5m2s

I'm fairly certain even from a good bit ago, bitwise did straight use this repo.

While similarities can be gained from MarkHC Simple Base, such as the ImGUI directx and the WinProc's matching formats, this is the origination of "bitwise." Compare this to the Simple base and you'll see similarities (might haves to look up older updates to both repo' to find some.)

**Comment by joolz23** [comment]
i used bitwise a long time ago and it did not look like anything in this repo, even now, it doesn't look like anything.

i compared it with mark hc simple base and yes, it looks just like it.

bitwise does not use this code whatsoever

**Comment by cantbeatme** [comment]
Do you know the colors of the chams in this cheat?
Or the style of the HP bars in the video I linked? Specifically their size and color changes?
I also like the blue-hand chams.

For final reference;
https://imgur.com/a/jHZUl

This will compare both menu's and options to TGF & Bitwise.

**Comment by joolz23** [comment]
you are seriously over analyzing the fuck out it

they both use the same menu base, it looks exactly like markhc simple base

even then, the menu/cheat has morphed so much since then. the picture/video you linked was the cheat in its very early stages. 

i don't think it's fair to say they ripped this entire base and compared it to those who actually ripped everything from this repo, and started selling it right off the bat. its just a retarded rumor rofl, lets get real here.

**Comment by A5-** [comment]
autism

**Comment by cantbeatme** [comment]
Yes, the first early stages looked almost identical to this base, with the same features, and in some sections they didn't even change the order of the menu items. Now, it looks more different, as they've changed more. 

So let's say I copy this entire repo and rename it, recolor, add some more dumb features and pass out my very own cheat. I then change the menu and add more and more useless features. Does this NOW mean it's not from this repo? Did I make my very own cheat not using anyone else as a baseline? Have I done everything myself? Or should I be on the list like all the other "cheat providers." The fact it was like this in the early stages means that it is this, but morphed. It still came from this.
