### ISSUE TITLE
tgf based cheat found

### ISSUE THREAD

**Issue by FaygoDreams** [A5-/Gamerfood_CSGO#104]
Link to cheat site:
http://insomniac.pw

"Progress" Report (how I found out):
https://imgur.com/a/PvYBJ

**Comment by cantbeatme** [comment]
Following the cheat title, it's " http://insomni.ac/ " which returns a 500 internal server error pointing back from insomni.vadis.hr , not entirely surprised that the domain registration comes from Croatia (assuming this is their host)

**Comment by A5-** [comment]
Thanks, added it to the list so if people search for it this will appear in search results
