### ISSUE TITLE
Crashes after load

### ISSUE THREAD

**Issue by bayouth** [A5-/Gamerfood_CSGO#105]
IDK if its just me but the latest version (or csgo update) causes TGF to close CSGO....

**Comment by cantbeatme** [comment]
Are you saying it's crashing? Or is CS:GO just closing?

**Comment by bayouth** [comment]
It's just closing, no crashes and attached debugger. Nothing out of the ordinary. I feel so stupid lol.

**Comment by steel4me** [comment]
Possible, have this too. But never first time when you open csgo, cause first match is always fine, csgo closes when you start a second or third match while conneting to server after finding a match.

I think it is some ingame check that fails somewhere near all I::Engine->IsInGame(); checks...

**Comment by bayouth** [comment]
Anything new?

**Comment by steel4me** [comment]
Nope, i only know that it is not related to changes i made...And i know that this crash wasn't there, it came up with some of last csgo updates. It is randomly and it has to do with Engine calls. It happens after you already played a game and crash's csgo when you play a second game, while connecting. Maybe some offsets / signatures? @cantbeatme , some ideas?

**Comment by cantbeatme** [comment]
@steel4me Not sure, I don't really get this issue. If I were to assume, make sure you check if they're alive before health and dormant and weapon, all that.

**Comment by steel4me** [comment]
At this point, when you forget alive check, it should crash every game you make...im already checking IsInGame and Alive everywhere, im looking a bit deeper...

Im not sure but is this normal:
Missing shutdown function for g_pMatchFramework->Init() : g_pMatchFramework->Shutdown()
"csgo.exe" (Win32): "...\Counter-Strike Global Offensive\bin\engine.dll" was unloaded.

**Comment by luis33k** [comment]
Exception thrown at 0x7598D0DC (kernel32.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x676E4556. Any help?

**Comment by luis33k** [comment]
Recently just started happening

**Comment by steel4me** [comment]
@cantbeatme it is true...i added recoil crosshair and fov circle, since ive added weaponsettings i check weaponid there too. Finally i've  attached debugger, so i was able to see that the breakpoint was near draw fov circle when connecting to game and don't check IsIngame && IsConnected leads to -> nullptr -> csgo crash -> csgo closing

/close please, thx
