### ISSUE TITLE
FPS drop when I enable visuals

### ISSUE THREAD

**Issue by luis33k** [A5-/Gamerfood_CSGO#106]
FPS drop when I enable visuals, anyone know to make it better? Cleaner code, etc.?

**Comment by cantbeatme** [comment]
So you turn on visuals, with nothing in visuals enabled, and your game just tanks?

**Comment by bonzobudy** [comment]
ya u haftu clean code. use abrasive cleaning agent, make sure to scrub hard and use lots of elbow grease.

**Comment by luis33k** [comment]
yup @cantbeatme

**Comment by cantbeatme** [comment]
If I were to take a shot in the dark, I don't think your computer is meant for this lol. But, the one thing that I've heard lag people in the past a heavy bit is glow. Try commenting [this line out](https://github.com/A5-/Gamerfood_CSGO/blob/master/csgo_internal/csgo_internal/Visuals.cpp#L34) and see if you get a difference.

**Comment by luis33k** [comment]
did you not read what i said, i run 256 fps on ever map lol my computer is meant for this game and many more sorry nothing personal but don’t offend me again

**Comment by A5-** [comment]
*teleports behind you with a katana* "Nothing personal kid"
