### ISSUE TITLE
efectcheats

### ISSUE THREAD

**Issue by zef9** [A5-/Gamerfood_CSGO#108]
https://high-minded.net/threads/efectcheats-net-slot-limited-personal-builds-vac-mm-streaming-mode.63015/

look in screenshots/media -> obs bypass -> 0:04 when he changes tabs the open vs project is called csgo_internal.
also this is made by certt, the creator of beardhook and other tgf based projects. still may be wrong tho

**Comment by cantbeatme** [comment]
Looks like this is it.

Completely off topic note, their loader for searches for DirectX, and just uses loadlibrary. Nothing really creative except ramming the file into Enigma, but even then he couldn't figure out how to properly use the encrypt strings function. 100% not by an English speaker. Actually finding now their loader just runs a directx env and runs imgui for some reason?? Got log info and other stuff like the position and size from the debug section the kid left in.

**Comment by A5-** [comment]
high level coding

**Comment by cantbeatme** [comment]
@A5- Don't even get me started on their amazing directx env "loader" fully packed with imgui, some true genuises at work, they could never just copy the directx example from the imgui repo and put loadlibrary in it
