### ISSUE TITLE
safe from new vac update?

### ISSUE THREAD

**Issue by unniggable** [A5-/Gamerfood_CSGO#114]
is this source detected by new vac modules?

**Comment by steel4me** [comment]
This source is detected anyway...Anyway, i know what you mean. VMT hooking is detected, thats what we read in several forums. I think the way how TGF hooks VMT is detected too but the strange thing is i made asia account with low trust factor and played many games, till now, no ban...

**Comment by unniggable** [comment]
I have changed quite a lot of the source and have been using it for a good few months with no bans. I'm seeing people getting hit with bans even without playing (guessing its just delayed) but me and a few of my friends who have been using the modified version of this source haven't been banned yet so i was just curious

**Comment by deadgirlsneversayno** [comment]
My 'cheat' it's pretty much the same base from Github minus the legitbot since I removed the silent aim and made the RCS functional rewriting only 7 lines of code and Im not banned yet. Truth is I don't use rage features, nor 0 visuals but so far so good.

**Comment by steel4me** [comment]
Im pretty sure this way of VMT hooking is detected. Myself and some friends got weird bans. We need a professional for rewriting part of the VMT hook to secure it. I've already tried but im lost with my experiance at this point.

**Comment by deadgirlsneversayno** [comment]
Hey, still here without any bans so far, could be true that the module loads only for low trust accounts? I've seen a lot people using crappy ayyware pastes with no problems. Im reading so many comments of people saying that only hooking to BaseClient/EngineClient is detected (or just calling from them). I lack the knowledge for toying around with that kind of stuff anyway, Im still using this cheat without any issues, I don't know if I'll get a ban eventually.

**Comment by steel4me** [comment]
Im sorting out at the moment, me and my friend was using my added smokecheck und bunnyhop. I've read that this could trigger something but i don't believe this somehow. This should end more or less in a untrusted ban not in "convicted by overwatch".

You use base an engine everywhere! Still a simple RCS would lead into a ban. Strange thing is that no one report a vac ban and all are playing only legit, i've disabled ragefeatures at the time ive read that. I've tested without bunny and smoke, legit with added aimtime, smooth and silent aim with fresh asia account, 4 MMs played and many casuals...this account got nothing till now it is difficult to say what happen exactly...

I say it is the VMT part and everyone will be hit with delay up to 2-4 weeks...

**Comment by unniggable** [comment]
Just yesterday my friend received a report while playing faceit (no cheats) and got a game ban and the last time he had ""my"" cheat injected was a month ago and hasn't injected since, I still haven't received a ban though, yeah I think people with low trust factor get the new modules as i'm pretty sure mine isn't low and I'm still fine

**Comment by deadgirlsneversayno** [comment]
Still good here, Im reading that the 'new' VAC module is from 2016 and it's not that new but anyway 0 problems thus far. Im now trying to update the stuff Panorama's update broke so hopefully this cheat can run for another couple of years.

**Comment by deadgirlsneversayno** [comment]
VAC'd here, it was a fun ride. GG.

**Comment by A5-** [comment]
If you got banned via VAC then it was due to your injection method

**Comment by unniggable** [comment]
What injection method are you guys using? and did you get banned or not?

**Comment by deadgirlsneversayno** [comment]
I used my shitty old injector, nothing too fancy, manual mapping I think. Couldn’t try or test any other injectors after the ban since Im living in the UK for now and left my PC with the panorama fixes at home. Id love to see what you guys have done with this cheat since these 3 months lol. Best regards and happy hacking.

**Comment by steel4me** [comment]
I have my own LL / MM injector and inject many things to many processes. If you don't use public injector and know what you do and / or use that over years it has nothing todo with your injector

**Comment by unniggable** [comment]
I will have a look now, thank you
