### ISSUE TITLE
panorama fix?

### ISSUE THREAD

**Issue by FrozGR** [A5-/Gamerfood_CSGO#116]
Could you add the panorama fix on this source & get it updated?

Thanks

**Comment by Jeimy041** [comment]
You can doit by yourself by changing all the client.dll to client_panorama.dll
tip: Use CTRL+H =)

**Comment by certmemer** [comment]
https://github.com/A5-/Gamerfood_CSGO/pull/117 ;]

**Comment by steel4me** [comment]
N1 fix, thx, works like a charm! Im inactive since march, regret that no one fixed vmt vtable, source still leads to VAC ban ;[

**Comment by certmemer** [comment]
commenting out framestage notify and drawmodelexecute is enough to make it ud though
for chams you can switch to drawmodel/sceneend

**Comment by unniggable** [comment]
hmm is there an alternative to FSN and DME?

**Comment by steel4me** [comment]
Would be nice to know, i also added PredictionSystem and BackTrack ... Why is FSN and DME "flagged" it is hooked the same way only difference is Client nad ModelRenderer, CreateMove is toggled over ClientMode...

So Prediction / BackTrack should not be affected (MoveHelper, Prediction, GameMovement).
I think im totally wrong with my brainstorm...

**Comment by unniggable** [comment]
I need FSN for third-person as well 😛 DME for chams etc but guess I'll have to comment that out for a while & I can't use CreateMove then?

**Comment by certmemer** [comment]
theres a list of detected modules @ unknowncheats, just find it
switch to drawmodel for chams, and you dont need fsn for 3rd person lol

**Comment by steel4me** [comment]
Okay, thx again, trying to find it. Let's see how long it takes till they monitor all modules :/

**Comment by unniggable** [comment]
commented out DME and FSN and been a couple of days and no ban... hm

**Comment by steel4me** [comment]
have no time for playing atm, remember the delay ban my friend...before you use it on your main 💯
