### ISSUE TITLE
open menu cursor bug

### ISSUE THREAD

**Issue by eliteironlix** [A5-/Gamerfood_CSGO#118]
Hi.
I have a problem like pressing a insert key.
After opening the menu in the game.
The menu opens but the cursor is still in the game and you cannot change any of the menu options in internal.

**Comment by unniggable** [comment]
cl_mouseenable has been removed, hook lockcursor
https://www.unknowncheats.me/forum/counterstrike-global-offensive/289333-panorama-locking-cursor.html
this may help you

**Comment by certmemer** [comment]
https://github.com/A5-/Gamerfood_CSGO/pull/117 paste this

**Comment by eliteironlix** [comment]
> #117 paste this

Thanks 👍
