### ISSUE TITLE
Penguware:

### ISSUE THREAD

**Issue by Classic1338** [A5-/Gamerfood_CSGO#122]
Just saying it now, Penguware doesn't use this src at all

**Comment by A5-** [comment]
Just saying it now, who cares?

**Comment by Classic1338** [comment]
Not a case of "who cares" it's an accusation, this could lower the sales he gets, which robs him of profits

**Comment by Fedorito** [comment]
Penguware is based on morphengine, which is based on TGF ok

**Comment by Fedorito** [comment]
So pengu = morph = tgf

**Comment by t9z** [comment]
> Not a case of "who cares" it's an accusation, this could lower the sales he gets, which robs him of profits

And that's very well deserved, he should not be getting any sales in the first place.
