### ISSUE TITLE
cannot open source file "d3dx9.h"

### ISSUE THREAD

**Issue by cleenixon** [A5-/Gamerfood_CSGO#125]
cannot open source file "d3dx9.h"

![image](https://user-images.githubusercontent.com/51036979/58376165-0e024e00-7f64-11e9-823c-4538f282c726.png)

**Comment by japnimedev** [comment]
Spoonfeeding time; download this DirectX June SDK https://www.microsoft.com/en-us/download/details.aspx?id=6812

Then add this shiz into the include folder, well search for it how.
