### ISSUE TITLE
Legit aimbot and anti aim bug

### ISSUE THREAD

**Issue by yashine59fr** [A5-/Gamerfood_CSGO#19]
everything work except anti aim and legit aimbot:
-when I enable anti aim it work but it move my camera really fast and I can see nothing
-legit aimbot don't work at all tried to change settings but triggerbot work
When I tried to compile tgf it gave me some errors : 
- "Engine->ClientCmd_Unrestricted don't take 1 argument" so I added , 0 and it solved the errors
- "dxd9.h not found" downloaded direct x sdk ( I got some error when I tried to install it so I found that I have to uninstall c++ redistribution 2012, then install direct x sdk 2010 and finally install back c++ redistribution 2012 )
I think it's because I should change something in project proprieties but idk what to change.
I fixed this errors but now legit aimbot and anti aim don't work.

I also changed this part of the code in NetvarManager.cpp 
```
void CNetVarManager::DumpNetvars()

{

	m_file.open("./netdump.txt");
	m_file << strenc("NetVar Dump by A5 / teamgamerfood\n\nhaha look proper formatting \n\n");

	for (ClientClass *pClass = I::Client->GetAllClasses(); pClass != NULL; pClass = pClass->m_pNext)
	{
		RecvTable *table = pClass->m_pRecvTable;
		DumpTable(table, 0);
	}

	m_file.close();
}
```
I also changed this part of the code in NetvarManager.h

```
class CNetVarManager
{
public:
	void Initialize();
	void GrabOffsets();
	int GetOffset(const char *tableName, const char *propName);
	bool HookProp(const char *tableName, const char *propName, RecvVarProxyFn fun);
	void DumpNetvars();
private:
	int Get_Prop(const char *tableName, const char *propName, RecvProp **prop = 0);
	int Get_Prop(RecvTable *recvTable, const char *propName, RecvProp **prop = 0);
	RecvTable *GetTable(const char *tableName);
	std::vector<RecvTable*> m_tables;
	void DumpTable(RecvTable *table, int depth);
	std::ofstream m_file;
};
```

**Comment by yashine59fr** [comment]
I solved this by reading UC comments in some threads but can't find how solve this bugs .

**Comment by cantbeatme** [comment]
When you turn on anti aim without silent aim, you will actually see it switching your angles.
To stop this, simply turn on Silent Aim!

**Comment by yashine59fr** [comment]
Thanks :)

**Comment by QWp6t** [comment]
this is why issues should be closed iirc

**Comment by cantbeatme** [comment]
You must understand that you're given the source, you have the ability to change everything you would like.
You can make it turn silent aim on automatically if you select anti aim, if Vars.Ragebot.SilentAim || Vars.Ragebot.AntiAim.Enabled

Please close the thread, you need to have more knowledge of what you're doing before you come asking an issue this simple.

**Comment by yashine59fr** [comment]
a

**Comment by yashine59fr** [comment]
When I eneable anti aim and silent aim it shot at random direction instead of where I aim

**Comment by yashine59fr** [comment]
I closed this issue 
sorry
