### ISSUE TITLE
Crashes after exiting?

### ISSUE THREAD

**Issue by vatutin** [A5-/Gamerfood_CSGO#22]
Hello,
CSGO crashes after I exit the game? Doesn't affect gameplay or anything just weird imo. I've found out it has something to do with creatematerial, dont know what exactly. If I comment out U::SetupTextures(); CSGO doesn't crash after closing. Any1 knows what to look for to fix this?

**Comment by cantbeatme** [comment]
>Exits game
>Game crashes
What? //Close

**Comment by vatutin** [comment]
Exactly, lol...
Is it just me then? I unload the cheat, close csgo and after the csgo window has closed I get a windows error saying that csgo.exe has just crashed. It's not exactly a problem, just kinda annoying. lol. I know this may sound like not a huge problem since it isn't, just asking out if others are experiencing the same thing and if there is some way to fix it?

**Comment by bazzz1512** [comment]
Did you change the original code?

**Comment by vatutin** [comment]
No I haven't, I fixed the errors and thats it. This doesn't seem like a common problem? Or don't people just take it as a problem since it kind of a isn't :D ? I just hate it and find it annoying how I get that application has stopped working popup after I've closed the whole damn application ^^

**Comment by ClaudiuHKS** [comment]
Yeah it crashes at exit. I had to

REGEDIT4

[HKEY_CURRENT_USER\Software\Microsoft\Windows\Windows Error Reporting]
"DontShowUI"=dword:00000001

**Comment by ClaudiuHKS** [comment]
if (g_bOffline && visible_flat) // (usually when in main menu of CSGO)
{
visible_flat->DecrementReferenceCount();
visible_flat->DeleteIfUnreferenced();
visible_flat->Release();
visible_flat = NULL;

visible_tex->DecrementReferenceCount();
visible_tex->DeleteIfUnreferenced();
visible_tex->Release();
visible_tex = NULL;

hidden_flat->DecrementReferenceCount();
hidden_flat->DeleteIfUnreferenced();
hidden_flat->Release();
hidden_flat = NULL;

hidden_tex->DecrementReferenceCount();
hidden_tex->DeleteIfUnreferenced();
hidden_tex->Release();
hidden_tex = NULL;
};

////////////////////////////


VOID WINAPI Hooks::DrawModelExecute(PVOID pCtx, PVOID pState, const ModelRenderInfo_t & _Info, matrix3x4_t * pCustomBoneToWorldOut)
{
	static std::string modelName = "";
	static CBaseEntity * pModelEntity = NULL;
	static INT iTeam = 0;
	static Color colHid, colVis, Colors[8];
	static bool bEnemy = false;
	static IMaterial * pMaterialA = NULL, *pMaterialB = NULL;

	H::ModelRender->UnHook();

	if (!g_bOffline && G::bAlive && !Vars.Misc.Streaming && _Info.pModel)
	{
		if (!visible_flat)
		{
			Colors[0] = Color(72, 219, 75, 128);
			Colors[1] = Color(232, 209, 32, 128);
			Colors[2] = Color(84, 167, 255, 128);
			Colors[3] = Color(200, 60, 60, 128);
			Colors[4] = Color(72, 219, 75);
			Colors[5] = Color(232, 209, 32);
			Colors[6] = Color(84, 167, 255);
			Colors[7] = Color(200, 60, 60);

			visible_flat = I::MaterialSystem->CreateMaterial(true, false);
			visible_tex = I::MaterialSystem->CreateMaterial(false, false);

			hidden_flat = I::MaterialSystem->CreateMaterial(true, true);
			hidden_tex = I::MaterialSystem->CreateMaterial(false, true);
		};

/// ...........................

**Comment by A5-** [comment]
Chill pay hack site using my source dude
http://hattrick.go.ro/about.php

**Comment by ClaudiuHKS** [comment]
I personally love your work and appreciate it. I specify inside the hack where the source code location is and which the authors are. I hope I am not causing you any personal problems by doing that. I just don't want everyone who needs a hack to learn compiling C/ C++ code in order to be able to..
