### ISSUE TITLE
Crashes on inject

### ISSUE THREAD

**Issue by unniggable** [A5-/Gamerfood_CSGO#24]
Cheat crashes when inject

**Comment by bazzz1512** [comment]
Maybe attach a debugger and see where it crashes?
PS. Csgo has a new compiler, so sigs and an interface broke

**Comment by unniggable** [comment]
Im attaching it and nothing comes up?

**Comment by unniggable** [comment]
not sure im doing it right though never done it before.

**Comment by deadgirlsneversayno** [comment]
@unniggable  Compile cheat in debug mode, attach visual studio's debugger to csgo, inject your cheat, game will crash and debugger will tell you exactly where it crashes.

The fix is posted at unknowncheats. Anyway here's a hint:

Offsets.cpp (2 signatures need a fix, others didn't change as far as I know, my build hasn't cras)
Autowall.cpp (tracetoexit has a new signature)
Util.cpp (I::Globals is not 0x53 anymore)

**Comment by unniggable** [comment]
hm my csgo doesn't crash when i attach in debug mode, could i have a link to this thread?

**Comment by deadgirlsneversayno** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/215034-csgo-compiler.html

**Comment by GravelPootis1** [comment]
omgggggggggggg

**Comment by unniggable** [comment]
It crashes at H::D3D9 = new VTHook((DWORD**)offsets.d3d9Device); 
-

offsets.d3d9Device = **(DWORD**)(U::FindPattern(strenc("shaderapidx9.dll"), strenc("A1 ?? ?? ?? ?? 50 8B 08 FF 51 0C")) + 1);

thats correct though isnt it?

**Comment by deadgirlsneversayno** [comment]
Correct.

**Comment by vatutin** [comment]
Kinda offtopic, but how do you debug this? When I compile in debug the cheat doesn't show at all when injecting

**Comment by deadgirlsneversayno** [comment]
the menu didn't appear for me neither at first, but as soon as I joined a server the game crashed.

**Comment by unniggable** [comment]
well even though that sig is correct my game is still crashing lol

**Comment by deadgirlsneversayno** [comment]
Glow and IsReadyEx changed again

**Comment by bazzz1512** [comment]
@deadgirlsneversayno Would be handier to commit the new sigs if you're already giving them out.
