### ISSUE TITLE
Compiling errors Help

### ISSUE THREAD

**Issue by GravelPootis1** [A5-/Gamerfood_CSGO#25]
log::

'<<': operator has no effect; expected operator with side-effect
csgo_internal\csgo_internal\netvarmanager.cpp 131   csgo_internal

'<<': illegal, right operand has type 'const char [66]'
csgo_internal\csgo_internal\netvarmanager.cpp 131   csgo_internal

'CNetVarManager::DumpTable': illegal call of non-static member function
csgo_internal\csgo_internal\netvarmanager.cpp 136   csgo_internal

left of '.close' must have class/struct/union
csgo_internal\csgo_internal\netvarmanager.cpp 138   csgo_internal

'CNetVarManager::m_file': non-standard syntax; use '&' to create a pointer to member
csgo_internal\csgo_internal\netvarmanager.cpp 131   csgo_internal

left of '.open' must have class/struct/union
csgo_internal\csgo_internal\netvarmanager.cpp 130   csgo_internal
'm_flRange': is not a member of 'WeaponInfo_t'

csgo_internal\csgo_internal\legitbot.cpp 147   csgo_internal
'void CNetVarManager::DumpNetvars(std::string)': overloaded member function not found in 'CNetVarManager'

csgo_internal\csgo_internal\netvarmanager.cpp 129   csgo_internal
the left brace '{' was unmatched at the end of the file

csgo_internal\csgo_internal\framestagenotify.cpp 6   csgo_internal

' ': unrecognized character escape sequence
csgo_internal\csgo_internal\util.cpp 54   csgo_internal

illegal reference to non-static member 'CNetVarManager::m_file'
csgo_internal\csgo_internal\netvarmanager.cpp 131   csgo_internal
-------------------------------------------------------------------------------
compiling using ci.appveyor, so any help please ?

**Comment by cantbeatme** [comment]
Problem is fixed here: #41 
Please close this. It's right next to the comment button down below 👍

**Comment by GravelPootis1** [comment]
Thanks
