### ISSUE TITLE
Show ranks

### ISSUE THREAD

**Issue by PhoNoTheSky** [A5-/Gamerfood_CSGO#35]
when i have show ranks enabled, and press tab the game crashes, i think the sig changed

**Comment by mDenis16** [comment]
Man. I have a older version .. From 3 weeks ago. It works perfectly.

**Comment by cantbeatme** [comment]
The [signature](https://github.com/A5-/Gamerfood_CSGO/blob/master/csgo_internal/csgo_internal/Offsets.cpp#L67) works fine for me, might be another problem.

**Comment by unniggable** [comment]
anyone figured this out?
