### ISSUE TITLE
Crash on menu when inject.

### ISSUE THREAD

**Issue by mDenis16** [A5-/Gamerfood_CSGO#39]
When i  am in menu and inject... Game crash
When I am on a server work.

**Comment by Jaeger33211** [comment]
if u send me fixed netvarmanager i can say whats the problem.   
and the heater

**Comment by PhoNoTheSky** [comment]
i have the same issue

**Comment by Jaeger33211** [comment]
Then send me ur netvarmanager.cpp 
My friend got the same problems and i fixed it just post ur code here

**Comment by mDenis16** [comment]
is clean

**Comment by Jaeger33211** [comment]
Yeah the errors arent shown i guess u got the error in netvarmanager
