### ISSUE TITLE
Info on Crashing.

### ISSUE THREAD

**Issue by cantbeatme** [A5-/Gamerfood_CSGO#42]
//Closed, can see information [here](https://github.com/A5-/Gamerfood_CSGO/pull/48#issuecomment-306398947)

An issue that's being reported is crashing at the main menu but in game it's perfectly fine.

This is due to [playsound](https://github.com/A5-/Gamerfood_CSGO/blob/master/csgo_internal/csgo_internal/PlaySound.cpp). Inject without updating anything (just to a working state) and make sure your menu opens, close the menu and hover over [THIS ](http://i.imgur.com/MEzn26c.png)button.

Should get a crash. My guess is (without any debug attempt at all) is we're calling U::IsReady(); anytime any sound file ending with beep.wav is called.

I've found these two sounds,
UI/counter_beep.wav
UI/competitive_accept_beep.wav

I believe the button (from picture above) calls UI/counter_beep.wav which then causes us to trigger the isready function, when it's not available, causing the game to crash.

I can't test, but this can probably be fixed by searching for "pt_beep.wav" instead of just "beep.wav" in playsound.cpp, since this is closer to the full string of competitive_accept_beep.wav

I'll leave this open so someone can test & report back on it.
*I may be wrong, counter_beep could be used for both, I'm not 100% sure, but I know this is the issues origination.

**Comment by PhoNoTheSky** [comment]
why not just search for competitive_accept_beep.wav anyways?

**Comment by PhoNoTheSky** [comment]
i have a fixed, disable the check, i don't need auto accept

**Comment by A5-** [comment]
The crash is happening because of the static string, since CSGO is multi-threaded this causes multiple initialisation of the string causing a crash.

Just debugging now to see what the new beep sound is called.

https://a.cocaine.ninja/ypxoso.png

Going to add a Log class to the cheat as well

**Comment by A5-** [comment]
https://a.cocaine.ninja/madurq.png

Output of the play sound hook

**Comment by cantbeatme** [comment]
Sorry I don't have an unbanned account so I can't actually get to the button lmao
