### ISSUE TITLE
Showing Mouse cursor ingame in the crosshair

### ISSUE THREAD

**Issue by Jaeger33211** [A5-/Gamerfood_CSGO#43]
The mouse cursor is flickering.

**Comment by Jaeger33211** [comment]
Also the mouse shows ingame in the menu
Not the csgo cursor the normal mouse cursor is bugged over the normal csgo cursor

**Comment by cantbeatme** [comment]
If the mouse cursor is flickering IN GAME, switch **multi-core** rendering in your **video options**.
If the problem persists, it's more than likely due to your computer not being able to keep up. Try lowering visual settings and other stuff to low and seeing if it still flickers.

**Comment by Jaeger33211** [comment]
Thanks helped 
/close pls
