### ISSUE TITLE
autostrafer is broken

### ISSUE THREAD

**Issue by retardlover** [A5-/Gamerfood_CSGO#44]
I cant fix it I spent like 2 minutes trying

**Comment by cantbeatme** [comment]
So you re-downloaded the entire sourced and tested, and autostrafer did not work?
Cause I just did, and it works just fine for me

**Comment by PhoNoTheSky** [comment]
autostrafer is a bit buggy, but this is meant to be a base for a hack, not use as is

**Comment by bazzz1512** [comment]
Autostrafer is fixed now
