### ISSUE TITLE
autostrafer

### ISSUE THREAD

**Issue by SM1LEXYZ** [A5-/Gamerfood_CSGO#46]
how to fix autostrafer?

**Comment by cantbeatme** [comment]
So you re-downloaded the entire source and tested, and autostrafer did not work?
Cause I just did, and it works just fine for me

P.S. Auto strafer DOES NOT INCREASE SPEED AUTOMATICALLY, IF YOU MOVE YOUR MOUSE LEFT OR RIGHT, IT WILL BASICALLY HOLD A/D TO "STRAFE" FOR YOU

**Comment by SM1LEXYZ** [comment]
no, with turned on AA autostrafe brokes

**Comment by ClaudiuHKS** [comment]
Try more CFixMove I suppose.

**Comment by bazzz1512** [comment]
Autostrafer is fixed now
