### ISSUE TITLE
VAC Detected/Update code

### ISSUE THREAD

**Issue by Spartan9077** [A5-/Gamerfood_CSGO#47]
Is this cheat VAC detected yet? Also, If it does get detected at some point of time, can I change the code myself to make it undetected again? Also would I be able to update the code to work after each update? (sorry for all of the noob questions)

**Comment by cantbeatme** [comment]
This repo is the entire source code without any license what so ever.
You get. The entire. Source.
Probably detected yes.
Yes to all of it.
//Close
