### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by ChristianTassoni97** [A5-/Gamerfood_CSGO#5]
Error "SseSqrt" function does not exist.

**Comment by ChristianTassoni97** [comment]
https://github.com/A5-/Gamerfood_CSGO/blob/master/csgo_internal/csgo_internal/Math.cpp#L18

Math.cpp, line 18

**Comment by Birdboat** [comment]
just change it u fuck

**Comment by A5-** [comment]
learn c++
