### ISSUE TITLE
how do i compile this cheat? 

### ISSUE THREAD

**Issue by reborn322** [A5-/Gamerfood_CSGO#51]

**Comment by certmemer** [comment]
you dont, youre retarded

**Comment by cantbeatme** [comment]
Have you looked at [google](http://lmgtfy.com/?q=How+do+I+compile+c%2B%2B+sources+windows)?

**Comment by GravelPootis1** [comment]
ci.appveyor.com online c++/c# compiler

**Comment by A5-** [comment]
you download the files and put them on a USB drive then place it into a microwave. Once you have it in there point the microwave towards your PC and turn on the microwave. The hack bin's will then be sent wirelessly via microwave frequencies to your PC

**Comment by Spartan9077** [comment]
![giphy](https://user-images.githubusercontent.com/26730202/27491727-bb04ac5c-5800-11e7-8b9c-0971b1ebbd06.gif)
