### ISSUE TITLE
why crash

### ISSUE THREAD

**Issue by SM1LEXYZ** [A5-/Gamerfood_CSGO#53]
void __stdcall Hooks::PaintTraverse( unsigned int panel, bool forceRepaint, bool allowForce, unsigned int vguiPanel)
{
	if (Vars.Visuals.CrosshairOn && !strcmp("HudZoom", I::VPanel->GetName(vguiPanel)))
		return;

	oPaintTraverse( panel , forceRepaint, allowForce, vguiPanel);

**Comment by SM1LEXYZ** [comment]
when inject>crash

**Comment by certmemer** [comment]
learn how calling conventions work and which one should you use, gtfo

**Comment by SM1LEXYZ** [comment]
just help me.
