### ISSUE TITLE
BSP Parsing falis at some times.

### ISSUE THREAD

**Issue by tempacc123** [A5-/Gamerfood_CSGO#57]
yeah as title. 

it confuses me so much. BSP parsing fails some times and csgo crashes at some times, after ending/sometimes mid MM match. am i only guy having this issue?

**Comment by A5-** [comment]
this doesn't use BSP parsing 🤔

**Comment by bazzz1512** [comment]
@A5- It is working, it's just[ falis](http://www.urbandictionary.com/define.php?term=falis)!
