### ISSUE TITLE
Some keys arent working for triggerbot/aimbotting

### ISSUE THREAD

**Issue by tempacc123** [A5-/Gamerfood_CSGO#58]
Idk why but 0x18 (Alt) key and maybe some other keys that i didnt find isnt working for enabling triggerbot/aimbot keys. anyone can confirm this?

**Comment by cantbeatme** [comment]
The answer can be fulfilled if you learned the coding language.

The reason is because in WndProc, uMsg for the ALT key being pressed will return WM_SYSKEYDOWN, NOT WM_KEYDOWN because it is a system related key (There is no case for WM_SYSKEYDOWN), such as alt tabbing and alt-windows, etc.

**Comment by tempacc123** [comment]
Thanks for solving, but i think triggerbot key as Mouse 3 also not working.
