### ISSUE TITLE
Doesnt works when i compile at debug mode

### ISSUE THREAD

**Issue by tempacc123** [A5-/Gamerfood_CSGO#59]
So yep im trying to fix my modified source so i compiled at debug mode. but at debug mode the menu doesnt shows up at all, and just crashes. 

Why this project doesnt works when compile at dbg mode?

**Comment by DarkAussieYT** [comment]
use release mode instead

**Comment by mtardal** [comment]
@DarkAussieYT How the hell do you expect him to DEBUG with the release dll?

**Comment by DarkAussieYT** [comment]
Well don't debug then

**Comment by mtardal** [comment]
@DarkAussieYT I can already debug, was just pointing out your useless and shitty advice.

**Comment by A5-** [comment]
You have to compile in release, you can still debug as long as you generate a pdb file and debug using Visual Studio by attaching it to CSGO

**Comment by tempacc123** [comment]
I still dont understands, isnt 

#define strenc( s ) ( s )
#define charenc( s ) ( s )
#define wstrenc( s ) ( s )
#define wcharenc( s ) ( s )

these should be used when i compile this as debug mode? why it crashes instead?

**Comment by DarkAussieYT** [comment]
The problem is that in debug mode, strenc,charenc,wstrenc,wcharenc all return the value you put in it
