### ISSUE TITLE
CMaterial::PrecacheVars VMT loading error happens when loading new map / CSGO Crashes.

### ISSUE THREAD

**Issue by tempacc123** [A5-/Gamerfood_CSGO#61]
alacewall01_-1824_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1984_1280_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1536_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1984_1376_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1120_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1344_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_640_480_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_640_64_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-704_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1664_992_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_816_2552_160
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1664_992_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1824_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-896_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-416_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1984_1376_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/metaldoor046a_640_64_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-416_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1984_1952_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_-800_-832_240
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_-448_-512_80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_64_-736_80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_64_-736_80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_1424_2152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_816_2552_160
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_1424_2152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_352_2136_160
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_816_2552_160
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_-800_-832_240
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_640_64_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_-448_-512_80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_640_896_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow048a_1408_992_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow005a_1408_992_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_-800_-832_240
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow005a_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow005a_-800_-832_240
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_1408_992_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_1424_2152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow005a_1424_2152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_nuke/nukwindowd_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/storefront_template/storefront_template001a_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_nuke/nukwindowd_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/metaldoor018a_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/metaldoor046a_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/storefront_template/storefront_template001a_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/metaldoor018a_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/metaldoor046a_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow005a_816_2552_160
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_1408_256_-80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_64_-736_80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow005a_64_-736_80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/glass/glasswindow005a_1408_256_-80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/metaldoor046a_-800_-832_240
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-800_-832_240
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_640_64_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/citadel_tilefloor016a_1408_256_-80
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_640_64_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/concrete/blend_blacktopsand_01_wvt_patch
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/nature/blend_sandhighway_01_wvt_patch
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1120_1120_16
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1344_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_-800_-832_240
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-896_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1120_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1824_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1984_1280_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1536_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1984_1376_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1120_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1344_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_640_480_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_640_64_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-704_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-1664_992_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/urban_metalwall01a_small_816_2552_160
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1664_992_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1824_1152_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-896_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-416_1440_-48
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/tilefloor02_-1984_1376_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_-2048_1056_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/cs_italy/hpe_stone_wall_02_top_-1664_544_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/metal/metaldoor046a_640_64_112
CMaterial::PrecacheVars: error loading vmt file for maps/de_dust2/de_dust/dust_palacewall01_-416_1440_-48

Strangely, the cheat or game tries to load previous map's VMT files when i tried to load new map and after some times csgo crashes.

**Comment by tempacc123** [comment]
And sorry, yes im Skid who cant fix this myself. apologize for that.

**Comment by tempacc123** [comment]
Nevermind it was my prop iterating code's problem. Sorry.

**Comment by A5-** [comment]
surprise surprise

**Comment by Skyline23** [comment]
you madr my day
