### ISSUE TITLE
Planted C4 Doesnt Glows.

### ISSUE THREAD

**Issue by tempacc123** [A5-/Gamerfood_CSGO#63]

**Comment by DarkAussieYT** [comment]
Its just a box around the bomb, what else do you want?

**Comment by tempacc123** [comment]
@DarkAussieYT I really dont know what are u talking about.

		case 108:
			if( Vars.Visuals.Filter.C4 )
				glowEntity->set( Color( 255, 39, 33, 250 ) );
			break;

why this code doesnt works? :(

**Comment by QWp6t** [comment]
That code works fine

**Comment by DarkAussieYT** [comment]
Enabled glow in settings

**Comment by tempacc123** [comment]
@DarkAussieYT OFC i did lol...

@QWp6t You sure?

**Comment by DarkAussieYT** [comment]
If you want it to work, do it you self, we are not your slaves, else use someone else's base

**Comment by Spartan9077** [comment]
@DarkAussieYT what is your YT channel link?

**Comment by tempacc123** [comment]
@DarkAussieYT ??? I never demend you to fix this issue nor to A5 or any contributers.
are u retarded or what?

**Comment by tempacc123** [comment]
https://imgur.com/a/rbhKK
