### ISSUE TITLE
Takes 10 years to join servers?

### ISSUE THREAD

**Issue by unniggable** [A5-/Gamerfood_CSGO#64]
Taking me years to join games anyone else getting this?

**Comment by tempacc123** [comment]
huh no?

**Comment by cantbeatme** [comment]
I question why you made an issue thread about this.
Go make a steam community thread about your extensive connection issue.

**Comment by A5-** [comment]
get better interweb my dude

**Comment by unniggable** [comment]
wasnt to do with my internet lol was no I::Engine->IsInGame()) so took ages to join game
