### ISSUE TITLE
Legitbot not work

### ISSUE THREAD

**Issue by 0ArturkA** [A5-/Gamerfood_CSGO#65]
Last version from github. Legit bot not work.

**Comment by tempacc123** [comment]
Yes it doesnt works like at first one minute but works after that.

idk why tho.

**Comment by 0ArturkA** [comment]
Wait 5 minutes. Not work.

**Comment by 0ArturkA** [comment]
@tempacc123 Wait 5 minutes. Not work.

**Comment by certmemer** [comment]
wait 6 then

**Comment by tempacc123** [comment]
Oh yeah. this also happened to me.
i think this is isvisible function's problem. Triggerbot shoots for target A, but legit aimbot doesnt. 

Test at aim_botz map guys. u will see what i am talking about.
