### ISSUE TITLE
Sometimes weapon ESP doesnt gets removed at next round 

### ISSUE THREAD

**Issue by tempacc123** [A5-/Gamerfood_CSGO#66]
https://imgur.com/a/3Jtbr

Like this. Sometimes happens but sometimes not.

**Comment by tempacc123** [comment]
https://imgur.com/a/id4n9

**Comment by GravelPootis1** [comment]
hud_reloadscheme

**Comment by cantbeatme** [comment]
@GravelPootis1 I thought that was only really useful in TF2 when world2screen would just fucking break on a map change until the game started

**Comment by tempacc123** [comment]
https://imgur.com/a/rbhKK

**Comment by GravelPootis1** [comment]
you need to prepare code

2017-06-24 8:14 GMT+02:00 TrashSkid <notifications@github.com>:
