### ISSUE TITLE
Rank ESP crashes game

### ISSUE THREAD

**Issue by unniggable** [A5-/Gamerfood_CSGO#67]
Anyone fixed the Rank ESP issue where is crashes the game when pressing tab? offsets.ServerRankRevealAllEx = U::FindPattern(strenc("client.dll"), strenc("8B EC 8B 0D ? ? ? ? 68")); thats the offset it should be fine?

**Comment by QWp6t** [comment]
That's not an offset. Hope this helps. :)

**Comment by unniggable** [comment]
i mean sig :)

**Comment by tempacc123** [comment]
55 8B EC 8B 0D ? ? ? ? 68 ? ? ? ?

**Comment by tempacc123** [comment]
me too :( really have no idea about this crash.
