### ISSUE TITLE
Noob questions

### ISSUE THREAD

**Issue by Spartan9077** [A5-/Gamerfood_CSGO#68]
Hey I have a noob question if anyone is willing to take the time to answer. So when I clone the repo, I just need to open the solution and build the project right?
TIA

**Comment by bazzz1512** [comment]
There is anti-paste the time I downloaded it

**Comment by bazzz1512** [comment]
There was anti-paste the time I downloaded it

**Comment by Spartan9077** [comment]
what does that mean?

**Comment by DarkAussieYT** [comment]
There is code that prevents copy pasters from using the code without under standing it, and fixing it

**Comment by Spartan9077** [comment]
well I would like to start learning C# and the .net framework, I am taking courses at treehouse which hopefully should teach me about these things

**Comment by Spartan9077** [comment]
also to update the offsets, would you edit the lines 62-68 in offsets.cpp?
(sorry for all of the noob questions)
