### ISSUE TITLE
Crashes after Textures setup

### ISSUE THREAD

**Issue by averyhugemen** [A5-/Gamerfood_CSGO#71]
Game crashes after textures setup
win10
Crash point: mov al, byte ptr ds:[edx]

**Comment by Spartan9077** [comment]
I cannot even get it to run, does the game have to be running for it to build correctly?

**Comment by certmemer** [comment]
yes, in a windowed mode

**Comment by Spartan9077** [comment]
ok i got it to run, and as you have confirmed, it does indeed crash XD.
