### ISSUE TITLE
Crashing 15 seconds after injection

### ISSUE THREAD

**Issue by plasmafart** [A5-/Gamerfood_CSGO#73]
It builds and injects but after I inject, there are no water marks or anything in game. and game crashes shortly after (no warning or error).

**Comment by QWp6t** [comment]
That's amazing!

**Comment by DarkAussieYT** [comment]
10/10

**Comment by unniggable** [comment]
debug it, could be a sig

**Comment by Vankxr** [comment]
did you get it to work?

**Comment by Spartan9077** [comment]
nope :(

**Comment by jribbink** [comment]
It works just fine.  Are you on release? Are you on 32 bit? Does your injector work?

**Comment by Vankxr** [comment]
Yea it works for me Now aswell

**Comment by cuteanimegals** [comment]
facing the same problem please help
