### ISSUE TITLE
p2c from TGF

### ISSUE THREAD

**Issue by bazzz1512** [A5-/Gamerfood_CSGO#74]
http://beardhook.xyz/

**Comment by unniggable** [comment]
fucking russians :)

**Comment by Spartan9077** [comment]
notice how static the entire one page site is

**Comment by unniggable** [comment]
"-Added function "Anti-Untrusted", protecting from "unreliable" status and should bypass the new the VAC " im pretty sure anti-untrusted has always been in the source

**Comment by cantbeatme** [comment]
"should bypass the new the VAC"
