### ISSUE TITLE
Changing the default ImGUI font

### ISSUE THREAD

**Issue by mtardal** [A5-/Gamerfood_CSGO#78]
Hello,

I'm trying to change the default font and Im trying to do so in GUI_Init, this is how I try to load the font:

`void GUI_Init(IDirect3DDevice9* pDevice)
{
	ImGui_ImplDX9_Init(G::Window, pDevice);

	ImGuiIO& io = ImGui::GetIO();
	ImGuiStyle& style = ImGui::GetStyle();
	ImFont* font = io.Fonts->AddFontFromMemoryCompressedTTF(Avalon_compressed_data, Avalon_compressed_size, 12.f);`

Game crashes as soon as it is injected, I tried adding different fonts etc, but they also make the game crash so I assume the problem isnt at my compressedTTF, I also tried calling the addfont at different places in the endscene, then the game doesnt crash but font doesnt change.

I literally spent hours on this. Where should I call the AddFont? What am I missing? Thanks a lot :/

**Comment by Skyline23** [comment]
Try to Debug it

**Comment by mtardal** [comment]
@Skyline23 I fixed the problem by hardcoding my font as the default one :P I'll try debugging and see what happens.

**Comment by mtardal** [comment]
Nvm, fixed the problem after debugging :P Thanks!
