### ISSUE TITLE
bitwise doesnt use ur source lol

### ISSUE THREAD

**Issue by mrfreaky123** [A5-/Gamerfood_CSGO#83]
i know that you're sad because your shitty cheat wont ever beat bitwise

**Comment by bighaxor** [comment]
Bitwise was based off of TGF it's common knowledge...

**Comment by unniggable** [comment]
mrfreaky you're dumb af bro lmfao

**Comment by mrfreaky123** [comment]
no it isn't dumbass

**Comment by unniggable** [comment]
and who tf are you?

**Comment by cantbeatme** [comment]
@A5- Can you close this thread? Personally believe it's misuse of the Issues section.
:)

**Comment by mrfreaky123** [comment]
it is an issue because it's not true dumbass

ur just mad that tgf will never have p resolver

**Comment by cantbeatme** [comment]
Yes, for you it's an "issue" but this is NOT where you put a verbal issue such as that.
https://guides.github.com/features/issues/

**Comment by A5-** [comment]
guessing he's the bitwise """""dev"""""

**Comment by mrfreaky123** [comment]
hows ur shitty resolver doing
