### ISSUE TITLE
Any fixed?

### ISSUE THREAD

**Issue by unniggable** [A5-/Gamerfood_CSGO#84]
Has anyone fixed the cheat after the update?

**Comment by DarkAussieYT** [comment]
nope, ive tried

**Comment by averyhugemen** [comment]
new CWeaponInfo_t
`class CWeaponInfo
{
public:
	char		pad_0x0000[4];			// 0x0000
	char*		consoleName;			// 0x0004
	char		pad_0008[12];			// 0x0008
	int			iMaxClip1;				// 0x0014
	int			iMaxClip2;				// 0x0018
	int			iDefaultClip1;			// 0x001C
	int			iDefaultClip2;			// 0x0020
	char		pad_0024[8];			// 0x0024
	char*		szWorldModel;			// 0x002C
	char*		szViewModel;			// 0x0030
	char*		szDroppedModel;			// 0x0034
	char		pad_0038[4];			// 0x0038
	char*		N0000023E;				// 0x003C
	char		pad_0040[56];			// 0x0040
	char*		szEmptySound;			// 0x0078
	char		pad_007C[4];			// 0x007C
	char*		szBulletType;			// 0x0080
	char		pad_0084[4];			// 0x0084
	char*		szHudName;				// 0x0088
	char*		szWeaponName;			// 0x008C
	char		pad_0090[56];			// 0x0090
	int 		WeaponType;				// 0x00C8
	int			iWeaponPrice;			// 0x00CC
	int			iKillAward;				// 0x00D0
	char*		szAnimationPrefix;		// 0x00D4
	float		flCycleTime;			// 0x00D8
	float		flCycleTimeAlt;			// 0x00DC
	float		flTimeToIdle;			// 0x00E0
	float		flIdleInterval;			// 0x00E4
	bool		bFullAuto;				// 0x00E8
	char		pad_0x00E5[3];			// 0x00E9
	int			iDamage;				// 0x00EC
	float		flArmorRatio;			// 0x00F0
	int			iBullets;				// 0x00F4
	float		flPenetration;			// 0x00F8
	float		flFlinchVelocityModifierLarge;	// 0x00FC
	float		flFlinchVelocityModifierSmall;	// 0x0100
	float		flRange;				// 0x0104
	float		flRangeModifier;		// 0x0108
	float		flThrowVelocity;		// 0x010C
	char		pad_0x010C[12];			// 0x0110
	bool		bHasSilencer;			// 0x011C
	char		pad_0x0119[3];			// 0x011D
	char*		pSilencerModel;			// 0x0120
	int			iCrosshairMinDistance;	// 0x0124
	int			iCrosshairDeltaDistance;// 0x0128 - iTeam?
	float		flMaxPlayerSpeed;		// 0x012C
	float		flMaxPlayerSpeedAlt;	// 0x0130
	float		flSpread;				// 0x0134
	float		flSpreadAlt;			// 0x0138
	float		flInaccuracyCrouch;		// 0x013C
	float		flInaccuracyCrouchAlt;	// 0x0140
	float		flInaccuracyStand;		// 0x0144
	float		flInaccuracyStandAlt;	// 0x0148
	float		flInaccuracyJumpInitial;// 0x014C
	float		flInaccuracyJump;		// 0x0150
	float		flInaccuracyJumpAlt;	// 0x0154
	float		flInaccuracyLand;		// 0x0158
	float		flInaccuracyLandAlt;	// 0x015C
	float		flInaccuracyLadder;		// 0x0160
	float		flInaccuracyLadderAlt;	// 0x0164
	float		flInaccuracyFire;		// 0x0168
	float		flInaccuracyFireAlt;	// 0x016C
	float		flInaccuracyMove;		// 0x0170
	float		flInaccuracyMoveAlt;	// 0x0174
	float		flInaccuracyReload;		// 0x0178
	int			iRecoilSeed;			// 0x017C
	float		flRecoilAngle;			// 0x0180
	float		flRecoilAngleAlt;		// 0x0184
	float		flRecoilAngleVariance;	// 0x0188
	float		flRecoilAngleVarianceAlt;	// 0x018C
	float		flRecoilMagnitude;		// 0x0190
	float		flRecoilMagnitudeAlt;	// 0x0194
	float		flRecoilMagnitudeVariance;	// 0x0198
	float		flRecoilMagnitudeVarianceAlt;	// 0x019C
	float		flRecoveryTimeCrouch;	// 0x01A0
	float		flRecoveryTimeStand;	// 0x01A4
	float		flRecoveryTimeCrouchFinal;	// 0x01A8
	float		flRecoveryTimeStandFinal;	// 0x01AC
	int			iRecoveryTransitionStartBullet;// 0x01B0 
	int			iRecoveryTransitionEndBullet;	// 0x01B4
	bool		bUnzoomAfterShot;		// 0x01B8
	bool		bHideViewModelZoomed;	// 0x01B9
	char		pad_0x01B5[2];			// 0x01BA
	char		iZoomLevels[3];			// 0x01BC
	int			iZoomFOV[2];			// 0x01C0
	float		fZoomTime[3];			// 0x01C4
	char*		szWeaponClass;			// 0x01D4
	float		flAddonScale;			// 0x01D8
	char		pad_0x01DC[4];			// 0x01DC
	char*		szEjectBrassEffect;		// 0x01E0
	char*		szTracerEffect;			// 0x01E4
	int			iTracerFrequency;		// 0x01E8
	int			iTracerFrequencyAlt;	// 0x01EC
	char*		szMuzzleFlashEffect_1stPerson; // 0x01F0
	char		pad_0x01F4[4];			 // 0x01F4
	char*		szMuzzleFlashEffect_3rdPerson; // 0x01F8
	char		pad_0x01FC[4];			// 0x01FC
	char*		szMuzzleSmokeEffect;	// 0x0200
	float		flHeatPerShot;			// 0x0204
	char*		szZoomInSound;			// 0x0208
	char*		szZoomOutSound;			// 0x020C
	float		flInaccuracyPitchShift;	// 0x0210
	float		flInaccuracySoundThreshold;	// 0x0214
	float		flBotAudibleRange;		// 0x0218
	BYTE		pad_0x0218[8];			// 0x0220
	char*		pWrongTeamMsg;			// 0x0224
	bool		bHasBurstMode;			// 0x0228
	BYTE		pad_0x0225[3];			// 0x0229
	bool		bIsRevolver;			// 0x022C
	bool		bCannotShootUnderwater;	// 0x0230
};`

LoadFromBuffer:
`bool KeyValues::LoadFromBuffer( KeyValues *pThis , const char *pszFirst , const char *pszSecond , PVOID pSomething , PVOID pAnother , PVOID pLast )
	{
		typedef bool( __thiscall *_LoadFromBuffer )( KeyValues* , const char* , const char* , PVOID , PVOID , PVOID );

		static _LoadFromBuffer LoadFromBufferFn = 0;
		static bool SearchFunction = false;

		if ( !SearchFunction )
		{
			DWORD dwFunctionAddress = CSX::Memory::FindPattern( CLIENT_DLL , "55 8B EC 83 E4 F8 83 EC 34 53 8B 5D 0C 89 4C 24 04" , 0 );

			if ( dwFunctionAddress )
			{
				LoadFromBufferFn = (_LoadFromBuffer)dwFunctionAddress;
				SearchFunction = true;
			}
		}`

Also:
`float GetSpread() { return get_vfunc<float(__thiscall*)(void*)>(this, 439)(this); }
		WeaponInfo_t* GetWeaponData() { return get_vfunc<WeaponInfo_t*(__thiscall*)(void*)>(this, 446)(this); }
		float GetInaccuracy() { return get_vfunc<float(__thiscall*)(void*)>(this, 469)(this); }
		void UpdateAccuracyPenalty() { get_vfunc<void(__thiscall*)(void*)>(this, 470)(this); }`

**Comment by DarkAussieYT** [comment]
Does that fix it all?, if so I will try

**Comment by steel4me** [comment]
Mhmhmhm...Ive tried many things now, i think i stuck with LoadFromBuffer,
Ive Updated Weapon Struct and how get weapon data is called.

```
WeaponInfo_t* CBaseCombatWeapon::GetCSWpnData( )
{
	if( !this ) return nullptr;

	typedef WeaponInfo_t*( __thiscall* OriginalFn )( void* );
	return U::GetVFunc<OriginalFn>(this, 446)(this);
	//return U::GetVFunc<OriginalFn>( this, 456 )( this ); //Wrong since update 18.08.17 
}
```

i also updated get weapon spread, but i don't use it anymore. but here it is.:

```
float CBaseCombatWeapon::GetWeaponSpread()
{
	if( !this )
		return 0.f;

	typedef float( __thiscall* OriginalFn )( void* );
	return U::GetVFunc<OriginalFn>( this, 439 )( this );
	//return U::GetVFunc<OriginalFn>( this, 479 )( this ); //Wrong since update 18.08.17 
}

```

Did someone change LoadFromBuffer and get it work?

**Comment by unniggable** [comment]
hm my GetWeaponID is not working?

**Comment by unniggable** [comment]
it isn't finding which gun is in my hand

**Comment by unniggable** [comment]
Weapon ESP is only showing knife aswell

**Comment by DarkAussieYT** [comment]
this is the fix for GetWeaponID, NetVars->GetOffset(XorStr("DT_BaseCombatWeapon"), XorStr("m_iItemDefinitionIndex"));

**Comment by DarkAussieYT** [comment]
https://www.unknowncheats.me/forum/1797115-post345.html

**Comment by DarkAussieYT** [comment]
int& CBaseCombatWeapon::GetWeaponID()
{
	return *( int* ) ( ( DWORD )this + offsets.m_iItemDefinitionIndex );
}

**Comment by tempacc123** [comment]
int CBaseCombatWeapon::GetAmmo()
{
	return *(int*)((DWORD)this + offsets.m_iClip1);
}

int CBaseCombatWeapon::GetAmmo2()
{
	return *(int*)((DWORD)this + offsets.m_iClip2);
}

this returns  Access violation reading location 0x00003204 when trying to read clip1.

Any ideas?

**Comment by tempacc123** [comment]
offsets.m_iClip1 = U::NetVars->GetOffset(XorStr("DT_BaseCombatWeapon"), XorStr("m_iClip1"));

**Comment by tempacc123** [comment]
Oh also,
I::VPanel = U::CaptureInterface<IVPanel>(strenc("vgui2.dll"), strenc("VGUI_Panel009"));
H::VPanel = new VTHook((DWORD**)I::VPanel);

Returns
Exception thrown at 0x745249AA (kernel32.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x00003730.

**Comment by unniggable** [comment]
i still have a problem with this

int& CBaseCombatWeapon::GetWeaponID()
{
	return *(int*)((DWORD)this + offsets.m_iItemDefinitionIndex);
}

my weapons config is not finding what gun i have in hand

**Comment by steel4me** [comment]
strange. i only tested some weapons against bots and everything was fine for me, but maybe im wrong!?
here is what i changed in offsets.cpp:

`offsets.m_iWeaponID = U::NetVars->GetOffset(charenc("DT_WeaponCSBase"), charenc("m_iItemDefinitionIndex"));`

just watch my fork from this repo and look at commits...
when i have time i will play casual and competetive to be really sure, but not today

**Comment by unniggable** [comment]
does G::LocalPlayer->GetWeapon()->GetWeaponID() work for you?

**Comment by A5-** [comment]
l2code & RE then ?________?

**Comment by unniggable** [comment]
nice help

**Comment by steel4me** [comment]
Heyhey, stop, always remain friendly ... you get free sourcecode for a good application. You probably would not be able to code a project like this at your self. As well as you have already received sufficient information to find your bug at your site. If you can not find it out, pay someone who can find it for you.

du lappen

**Comment by unniggable** [comment]
that doesn't even make sense. I'm asking does a piece of code work for anyone if you can't give a simple yes/no answer then don't comment.

**Comment by steel4me** [comment]
i gave you already the answer. watch my fork, watch my commits, watch my comments, with this changes for me it works! i get correct weapon id and names, everything is fine, trigger is fine, aimer is fine, autowall is fine. what do you want?

**Comment by NeoxV2** [comment]
Big credits to @steel4me !! Thanks for uploading your fork with the working source!! Great job you did! :) Just some small bugs left (which aren't yours) then the Source is fine. Thnaks again.

**Comment by A5-** [comment]
Merged fork into master
