### ISSUE TITLE
BeardHook P2C self-leak lol

### ISSUE THREAD

**Issue by Martymoose98** [A5-/Gamerfood_CSGO#87]
https://www.unknowncheats.me/forum/cs-go-releases/229403-beardhook-selfleaked.html

Apparently, the owner decided it was time to 'self-leak their'cheat. The website is also taken down too (for the most part). He also gives no credits in his post.

Just an update because A5 explicitly states "Please open issues of found ones so I can link them in here". Idk if this qualifies anymore.

**Comment by A5-** [comment]
yeah lol that source is a complete rip of this

**Comment by Martymoose98** [comment]
I guess it wasn't selling : ^)

**Comment by Martymoose98** [comment]
Guess it wasn't selling lmao.
