### ISSUE TITLE
how to load cheat

### ISSUE THREAD

**Issue by ilovegame1985** [A5-/Gamerfood_CSGO#88]

**Comment by Spartan9077** [comment]
Preheat for approximately 1 minute in microwave in plastic wrapper with one side open on high power settings, remove from microwave and rotate to ensure even distribution of heat. Place burrito back in microwave and set the timer to 1:15. After the burrito has been sufficiently heated, place on paper plate and wait for 5 minutes to allow product to cool. Enjoy your very own Joe's Hoe's Burritos!!!

**Comment by ChtThX** [comment]
You need to have an injector.

**Comment by cantbeatme** [comment]
//Close @A5-
