### ISSUE TITLE
create injector and how to include new features?

### ISSUE THREAD

**Issue by ChtThX** [A5-/Gamerfood_CSGO#90]
Can anyone tell me how I can create an injector and insert new features?
I also want to know if I need to encrypt the dll and the injector. Thank you!
@A5- @SippieCup @cantbeatme

**Comment by Skyline23** [comment]
www.google.com & www.learncpp.com.

**Comment by ChtThX** [comment]
Oh! You helped me a lot! You are the man!

**Comment by SippieCup** [comment]
message me on gitter.im

**Comment by A5-** [comment]
wtf is gitter.im

**Comment by bazzz1512** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682437(v=vs.85).aspx

**Comment by cantbeatme** [comment]
@A5- https://github.com/gitterHQ it's like discord but for github users kinda
