### ISSUE TITLE
autoscope

### ISSUE THREAD

**Issue by premiumpastingforp2c** [A5-/Gamerfood_CSGO#92]
i added auto scope by pasting it from beardhook source 
but when i open the menu now and enable it it automaticly disables when i enable ragebot 
anybody got any clue?

**Comment by cantbeatme** [comment]
Check for basic if-else statements?
Ensure no second item on the menu matches the exact name? ?
Make sure it has its own variable (bool) ???

**Comment by premiumpastingforp2c** [comment]
if (Vars.Ragebot.AutoScope && G::LocalPlayer->GetWeapon()->IsGunCanScope() && !(G::LocalPlayer->IsScoped()))
	{
		G::UserCmd->buttons |= IN_ATTACK2;
	}

**Comment by premiumpastingforp2c** [comment]
this is the code i use
and the variable checks out
