### ISSUE TITLE
FIX CHEAT

### ISSUE THREAD

**Issue by mDenis16** [A5-/Gamerfood_CSGO#93]
PLEASE FIX CHEAT
CHEAT IS BROKEN.

**Comment by premiumpastingforp2c** [comment]
what is broken?

**Comment by mDenis16** [comment]
ragebot
and menu not working when i compile

**Comment by mDenis16** [comment]
can u give me a tgf fixed? all working?

**Comment by mDenis16** [comment]
is closing after press insert

**Comment by premiumpastingforp2c** [comment]
just download the latest compile it in virtual studio 2017 in release mode and that one works

**Comment by cantbeatme** [comment]
//Close @A5-
