### ISSUE TITLE
code auto accept and no flash

### ISSUE THREAD

**Issue by ChtThX** [A5-/Gamerfood_CSGO#94]
Can someone tell me where is the code for auto accept and flash? thank you!

**Comment by sonicrules11** [comment]
Just go look for a while on google mate

**Comment by cantbeatme** [comment]
[Auto Accept](https://github.com/A5-/Gamerfood_CSGO/blob/master/csgo_internal/csgo_internal/PlaySound.cpp)
[Flash](https://github.com/A5-/Gamerfood_CSGO/blob/master/csgo_internal/csgo_internal/DrawModelExecute.cpp#L52)

**Comment by ChtThX** [comment]
@cantbeatme thank you so much! I've seen it here but the problem is that one thing depends on the other ... it's not enough just to add these codes to the project ... I think. Or just do it? for example, the function isready ... not got ready in the project I have.

**Comment by cantbeatme** [comment]
isready uses the "isreadyex" signature to find the function
https://github.com/A5-/Gamerfood_CSGO/blob/c5aa0ccdebf0dff8c1a87118574df97ea4341722/csgo_internal/csgo_internal/Offsets.cpp#L68

**Comment by ChtThX** [comment]
@cantbeatme 
please send me your e-mail so that I can show you the project. thank you!
