### ISSUE TITLE
anyone whos tried making a resolver got this problem?

### ISSUE THREAD

**Issue by unniggable** [A5-/Gamerfood_CSGO#98]
pEntity->GetEyeAngles().y = pEntity->GetLowerBodyYaw() - 15;
with the first pEntity i get the error 

"CBaseEntity *pEntity 
expression must be a modifiable lvalue"

anyone know anything?

**Comment by cantbeatme** [comment]
Take a closer look at the GetEyeAngles() function itself.
The error tells you exactly what's wrong, it's not modifiable, but for what reason is the question.

**Comment by unniggable** [comment]
QAngle CBaseEntity::GetEyeAngles()
{
	return *(QAngle*)((DWORD)this + offsets.m_angEyeAngles);
}

i dont see anything wrong with it

**Comment by cantbeatme** [comment]
There's nothing inherently "wrong" with it.
The problem comes with the way you're trying to use it.

**Comment by unniggable** [comment]
How else could i do it? I've checked other sources and they can do that without any problem and its also not setting the angles of the other players

**Comment by cantbeatme** [comment]
See, I want to hint on exactly what's wrong, but it's hard without making it a dead giveaway.

This is about as hint-worthy as I can make it,

In the function under Entity.cpp, you CANNOT directly edit  `GetTeam()` without getting the exact same error. But, YOU CAN EDIT `GetFallbackStatTrak()`.

The answer you're needing is at the base of the language, this should be the most simple thing to find, you need to learn before you work. Questions like this have also been stated on stackoverflow many many times, easily found by google.

http://www.cplusplus.com/
http://www.cplusplus.com/doc/tutorial/pointers/
http://www.cplusplus.com/doc/tutorial/dynamic/

**Comment by unniggable** [comment]
Alright i think it might be working other than my game randomly closing

**Comment by A5-** [comment]
You're de-referencing the pointer to the value

**Comment by SippieCup** [comment]
In case you are still confused..
```
vecEyeAngles = (QAngle*)((DWORD)Entity + offsets.m_angEyeAngles);
```
