### ISSUE TITLE
https://cr0nus.net/

### ISSUE THREAD

**Issue by eue398** [A5-/Gamerfood_CSGO#99]
https://cr0nus.net/

source got leaked its tgf and ayyware

**Comment by cantbeatme** [comment]
Looks like it's mainly ayyware - 
https://youtu.be/-dHeveymcQY?t=36s

**Comment by NoireCS** [comment]
https://github.com/constcycle/cr0nus
free sauce

**Comment by eue398** [comment]
@cantbeatme that menu is the only non pasted thing its drawn with d3d not surface

**Comment by tomsyyy** [comment]
Is there source for the build 19?
